grid_type = {
    'OCCUPIED' : 1,
    'UNOCCUPIED' : 2,
    'UNEXPLORED' : 0
}

color_dict = {
    'OCCUPIED'   : (150, 150, 150),
    'UNOCCUPIED' : (50, 50, 50),
    'UNEXPLORED' : (0, 0, 0)
}

ENABLE_DYNAMIC = False
N_AGENTS = 6
PEDESTRIAN_MAX_SPEED = 30
PEDESTRIAN_RADIUS = 8

DRONE_RADIUS = 4
DRONE_MAX_SPEED = 20