/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCES_NLP_solver_model_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real FORCES_NLP_solver_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[15] = {1, 7, 0, 1, 1, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[20] = {4, 7, 0, 0, 2, 4, 5, 6, 8, 10, 0, 2, 1, 3, 0, 1, 0, 2, 1, 3};
static const casadi_int casadi_s6[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s7[25] = {5, 7, 0, 5, 5, 5, 10, 15, 15, 15, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4};

/* FORCES_NLP_solver_objective_0:(i0[7],i1[15])->(o0,o1[1x7,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[0]? arg[0][3] : 0;
  a1=240.;
  a0=(a0-a1);
  a1=casadi_sq(a0);
  a2=arg[0]? arg[0][4] : 0;
  a3=605.;
  a2=(a2-a3);
  a3=casadi_sq(a2);
  a1=(a1+a3);
  a3=arg[0]? arg[0][5] : 0;
  a4=casadi_sq(a3);
  a1=(a1+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=casadi_sq(a4);
  a1=(a1+a5);
  a5=1000.;
  a6=arg[0]? arg[0][0] : 0;
  a6=(a5*a6);
  a1=(a1+a6);
  if (res[0]!=0) res[0][0]=a1;
  if (res[1]!=0) res[1][0]=a5;
  a0=(a0+a0);
  if (res[1]!=0) res[1][1]=a0;
  a2=(a2+a2);
  if (res[1]!=0) res[1][2]=a2;
  a3=(a3+a3);
  if (res[1]!=0) res[1][3]=a3;
  a4=(a4+a4);
  if (res[1]!=0) res[1][4]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_0_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_0_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_0_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_0_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_0_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_0_incref(void) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_0_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_objective_0_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_objective_0_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real FORCES_NLP_solver_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_dynamics_0:(i0[7],i1[15])->(o0[4],o1[4x7,10nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=arg[0]? arg[0][3] : 0;
  a1=1.0000000000000001e-01;
  a2=arg[0]? arg[0][5] : 0;
  a3=(a1*a2);
  a0=(a0+a3);
  a3=5.0000000000000010e-03;
  a4=arg[0]? arg[0][1] : 0;
  a5=(a3*a4);
  a0=(a0+a5);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a5=arg[0]? arg[0][6] : 0;
  a6=(a1*a5);
  a0=(a0+a6);
  a6=arg[0]? arg[0][2] : 0;
  a7=(a3*a6);
  a0=(a0+a7);
  if (res[0]!=0) res[0][1]=a0;
  a4=(a1*a4);
  a2=(a2+a4);
  if (res[0]!=0) res[0][2]=a2;
  a6=(a1*a6);
  a5=(a5+a6);
  if (res[0]!=0) res[0][3]=a5;
  if (res[1]!=0) res[1][0]=a3;
  if (res[1]!=0) res[1][1]=a1;
  if (res[1]!=0) res[1][2]=a3;
  if (res[1]!=0) res[1][3]=a1;
  a3=1.;
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a3;
  if (res[1]!=0) res[1][6]=a1;
  if (res[1]!=0) res[1][7]=a3;
  if (res[1]!=0) res[1][8]=a1;
  if (res[1]!=0) res[1][9]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_dynamics_0_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_dynamics_0_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_dynamics_0_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_dynamics_0_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_dynamics_0_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_dynamics_0_incref(void) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_dynamics_0_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_dynamics_0_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_dynamics_0_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real FORCES_NLP_solver_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_inequalities_0:(i0[7],i1[15])->(o0[5],o1[5x7,15nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0-a1);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][4] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a4=(a3-a4);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a5=arg[1]? arg[1][2] : 0;
  a5=casadi_sq(a5);
  a2=(a2-a5);
  a5=arg[0]? arg[0][0] : 0;
  a2=(a2+a5);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[1]? arg[1][3] : 0;
  a2=(a0-a2);
  a6=casadi_sq(a2);
  a7=arg[1]? arg[1][4] : 0;
  a7=(a3-a7);
  a8=casadi_sq(a7);
  a6=(a6+a8);
  a8=arg[1]? arg[1][5] : 0;
  a8=casadi_sq(a8);
  a6=(a6-a8);
  a6=(a6+a5);
  if (res[0]!=0) res[0][1]=a6;
  a6=arg[1]? arg[1][6] : 0;
  a6=(a0-a6);
  a8=casadi_sq(a6);
  a9=arg[1]? arg[1][7] : 0;
  a9=(a3-a9);
  a10=casadi_sq(a9);
  a8=(a8+a10);
  a10=arg[1]? arg[1][8] : 0;
  a10=casadi_sq(a10);
  a8=(a8-a10);
  a8=(a8+a5);
  if (res[0]!=0) res[0][2]=a8;
  a8=arg[1]? arg[1][9] : 0;
  a8=(a0-a8);
  a10=casadi_sq(a8);
  a11=arg[1]? arg[1][10] : 0;
  a11=(a3-a11);
  a12=casadi_sq(a11);
  a10=(a10+a12);
  a12=arg[1]? arg[1][11] : 0;
  a12=casadi_sq(a12);
  a10=(a10-a12);
  a10=(a10+a5);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[1]? arg[1][12] : 0;
  a0=(a0-a10);
  a10=casadi_sq(a0);
  a12=arg[1]? arg[1][13] : 0;
  a3=(a3-a12);
  a12=casadi_sq(a3);
  a10=(a10+a12);
  a12=arg[1]? arg[1][14] : 0;
  a12=casadi_sq(a12);
  a10=(a10-a12);
  a10=(a10+a5);
  if (res[0]!=0) res[0][4]=a10;
  a10=1.;
  if (res[1]!=0) res[1][0]=a10;
  if (res[1]!=0) res[1][1]=a10;
  if (res[1]!=0) res[1][2]=a10;
  if (res[1]!=0) res[1][3]=a10;
  if (res[1]!=0) res[1][4]=a10;
  a1=(a1+a1);
  if (res[1]!=0) res[1][5]=a1;
  a2=(a2+a2);
  if (res[1]!=0) res[1][6]=a2;
  a6=(a6+a6);
  if (res[1]!=0) res[1][7]=a6;
  a8=(a8+a8);
  if (res[1]!=0) res[1][8]=a8;
  a0=(a0+a0);
  if (res[1]!=0) res[1][9]=a0;
  a4=(a4+a4);
  if (res[1]!=0) res[1][10]=a4;
  a7=(a7+a7);
  if (res[1]!=0) res[1][11]=a7;
  a9=(a9+a9);
  if (res[1]!=0) res[1][12]=a9;
  a11=(a11+a11);
  if (res[1]!=0) res[1][13]=a11;
  a3=(a3+a3);
  if (res[1]!=0) res[1][14]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_0_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_0_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_0_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_0_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_0_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_0_incref(void) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_0_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_inequalities_0_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_inequalities_0_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real FORCES_NLP_solver_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_objective_1:(i0[7],i1[15])->(o0,o1[1x7,5nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6;
  a0=arg[0]? arg[0][3] : 0;
  a1=240.;
  a0=(a0-a1);
  a1=casadi_sq(a0);
  a2=arg[0]? arg[0][4] : 0;
  a3=605.;
  a2=(a2-a3);
  a3=casadi_sq(a2);
  a1=(a1+a3);
  a3=arg[0]? arg[0][5] : 0;
  a4=casadi_sq(a3);
  a1=(a1+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=casadi_sq(a4);
  a1=(a1+a5);
  a5=1000.;
  a6=arg[0]? arg[0][0] : 0;
  a6=(a5*a6);
  a1=(a1+a6);
  if (res[0]!=0) res[0][0]=a1;
  if (res[1]!=0) res[1][0]=a5;
  a0=(a0+a0);
  if (res[1]!=0) res[1][1]=a0;
  a2=(a2+a2);
  if (res[1]!=0) res[1][2]=a2;
  a3=(a3+a3);
  if (res[1]!=0) res[1][3]=a3;
  a4=(a4+a4);
  if (res[1]!=0) res[1][4]=a4;
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_1_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_1_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_1_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_1_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_1_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_1_incref(void) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_objective_1_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_objective_1_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_objective_1_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real FORCES_NLP_solver_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCES_NLP_solver_inequalities_1:(i0[7],i1[15])->(o0[5],o1[5x7,15nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a1=(a0-a1);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][4] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a4=(a3-a4);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a5=arg[1]? arg[1][2] : 0;
  a5=casadi_sq(a5);
  a2=(a2-a5);
  a5=arg[0]? arg[0][0] : 0;
  a2=(a2+a5);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[1]? arg[1][3] : 0;
  a2=(a0-a2);
  a6=casadi_sq(a2);
  a7=arg[1]? arg[1][4] : 0;
  a7=(a3-a7);
  a8=casadi_sq(a7);
  a6=(a6+a8);
  a8=arg[1]? arg[1][5] : 0;
  a8=casadi_sq(a8);
  a6=(a6-a8);
  a6=(a6+a5);
  if (res[0]!=0) res[0][1]=a6;
  a6=arg[1]? arg[1][6] : 0;
  a6=(a0-a6);
  a8=casadi_sq(a6);
  a9=arg[1]? arg[1][7] : 0;
  a9=(a3-a9);
  a10=casadi_sq(a9);
  a8=(a8+a10);
  a10=arg[1]? arg[1][8] : 0;
  a10=casadi_sq(a10);
  a8=(a8-a10);
  a8=(a8+a5);
  if (res[0]!=0) res[0][2]=a8;
  a8=arg[1]? arg[1][9] : 0;
  a8=(a0-a8);
  a10=casadi_sq(a8);
  a11=arg[1]? arg[1][10] : 0;
  a11=(a3-a11);
  a12=casadi_sq(a11);
  a10=(a10+a12);
  a12=arg[1]? arg[1][11] : 0;
  a12=casadi_sq(a12);
  a10=(a10-a12);
  a10=(a10+a5);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[1]? arg[1][12] : 0;
  a0=(a0-a10);
  a10=casadi_sq(a0);
  a12=arg[1]? arg[1][13] : 0;
  a3=(a3-a12);
  a12=casadi_sq(a3);
  a10=(a10+a12);
  a12=arg[1]? arg[1][14] : 0;
  a12=casadi_sq(a12);
  a10=(a10-a12);
  a10=(a10+a5);
  if (res[0]!=0) res[0][4]=a10;
  a10=1.;
  if (res[1]!=0) res[1][0]=a10;
  if (res[1]!=0) res[1][1]=a10;
  if (res[1]!=0) res[1][2]=a10;
  if (res[1]!=0) res[1][3]=a10;
  if (res[1]!=0) res[1][4]=a10;
  a1=(a1+a1);
  if (res[1]!=0) res[1][5]=a1;
  a2=(a2+a2);
  if (res[1]!=0) res[1][6]=a2;
  a6=(a6+a6);
  if (res[1]!=0) res[1][7]=a6;
  a8=(a8+a8);
  if (res[1]!=0) res[1][8]=a8;
  a0=(a0+a0);
  if (res[1]!=0) res[1][9]=a0;
  a4=(a4+a4);
  if (res[1]!=0) res[1][10]=a4;
  a7=(a7+a7);
  if (res[1]!=0) res[1][11]=a7;
  a9=(a9+a9);
  if (res[1]!=0) res[1][12]=a9;
  a11=(a11+a11);
  if (res[1]!=0) res[1][13]=a11;
  a3=(a3+a3);
  if (res[1]!=0) res[1][14]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_1_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_1_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_1_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_1_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_1_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_1_incref(void) {
}

CASADI_SYMBOL_EXPORT void FORCES_NLP_solver_inequalities_1_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_inequalities_1_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int FORCES_NLP_solver_inequalities_1_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real FORCES_NLP_solver_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FORCES_NLP_solver_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FORCES_NLP_solver_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FORCES_NLP_solver_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
