/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) MPC_SOLVER_model_ ## ID
#endif

#include <math.h> 
#include "MPC_SOLVER_model.h"

#ifndef casadi_real
#define casadi_real MPC_SOLVER_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[30] = {26, 1, 0, 26, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[15] = {1, 7, 0, 1, 1, 1, 2, 3, 4, 5, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s5[20] = {4, 7, 0, 0, 2, 4, 5, 6, 8, 10, 0, 2, 1, 3, 0, 1, 0, 2, 1, 3};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[27] = {6, 7, 0, 5, 5, 5, 10, 15, 16, 17, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 5};

/* MPC_SOLVER_objective_0:(i0[7],i1[26])->(o0,o1[1x7,5nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][3] : 0;
  a2=240.;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a2=(a3*a1);
  a4=arg[0]? arg[0][4] : 0;
  a5=605.;
  a6=(a4-a5);
  a6=(a0*a6);
  a4=(a4-a5);
  a5=(a6*a4);
  a2=(a2+a5);
  a5=arg[0]? arg[0][5] : 0;
  a7=(a0*a5);
  a8=(a7*a5);
  a2=(a2+a8);
  a8=arg[0]? arg[0][6] : 0;
  a9=(a0*a8);
  a10=(a9*a8);
  a2=(a2+a10);
  a10=arg[0]? arg[0][0] : 0;
  a2=(a2+a10);
  if (res[0]!=0) res[0][0]=a2;
  a2=1.;
  if (res[1]!=0) res[1][0]=a2;
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[1]!=0) res[1][1]=a3;
  a4=(a0*a4);
  a6=(a6+a4);
  if (res[1]!=0) res[1][2]=a6;
  a5=(a0*a5);
  a7=(a7+a5);
  if (res[1]!=0) res[1][3]=a7;
  a0=(a0*a8);
  a9=(a9+a0);
  if (res[1]!=0) res[1][4]=a9;
  return 0;
}

int MPC_SOLVER_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int MPC_SOLVER_objective_0_alloc_mem(void) {
  return 0;
}

int MPC_SOLVER_objective_0_init_mem(int mem) {
  return 0;
}

void MPC_SOLVER_objective_0_free_mem(int mem) {
}

int MPC_SOLVER_objective_0_checkout(void) {
  return 0;
}

void MPC_SOLVER_objective_0_release(int mem) {
}

void MPC_SOLVER_objective_0_incref(void) {
}

void MPC_SOLVER_objective_0_decref(void) {
}

casadi_int MPC_SOLVER_objective_0_n_in(void) { return 2;}

casadi_int MPC_SOLVER_objective_0_n_out(void) { return 2;}

casadi_real MPC_SOLVER_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* MPC_SOLVER_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* MPC_SOLVER_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int MPC_SOLVER_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* MPC_SOLVER_dynamics_0:(i0[7],i1[26])->(o0[4],o1[4x7,10nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7;
  a0=arg[0]? arg[0][3] : 0;
  a1=1.0000000000000001e-01;
  a2=arg[0]? arg[0][5] : 0;
  a3=(a1*a2);
  a0=(a0+a3);
  a3=5.0000000000000010e-03;
  a4=arg[0]? arg[0][1] : 0;
  a5=(a3*a4);
  a0=(a0+a5);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  a5=arg[0]? arg[0][6] : 0;
  a6=(a1*a5);
  a0=(a0+a6);
  a6=arg[0]? arg[0][2] : 0;
  a7=(a3*a6);
  a0=(a0+a7);
  if (res[0]!=0) res[0][1]=a0;
  a4=(a1*a4);
  a2=(a2+a4);
  if (res[0]!=0) res[0][2]=a2;
  a6=(a1*a6);
  a5=(a5+a6);
  if (res[0]!=0) res[0][3]=a5;
  if (res[1]!=0) res[1][0]=a3;
  if (res[1]!=0) res[1][1]=a1;
  if (res[1]!=0) res[1][2]=a3;
  if (res[1]!=0) res[1][3]=a1;
  a3=1.;
  if (res[1]!=0) res[1][4]=a3;
  if (res[1]!=0) res[1][5]=a3;
  if (res[1]!=0) res[1][6]=a1;
  if (res[1]!=0) res[1][7]=a3;
  if (res[1]!=0) res[1][8]=a1;
  if (res[1]!=0) res[1][9]=a3;
  return 0;
}

int MPC_SOLVER_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int MPC_SOLVER_dynamics_0_alloc_mem(void) {
  return 0;
}

int MPC_SOLVER_dynamics_0_init_mem(int mem) {
  return 0;
}

void MPC_SOLVER_dynamics_0_free_mem(int mem) {
}

int MPC_SOLVER_dynamics_0_checkout(void) {
  return 0;
}

void MPC_SOLVER_dynamics_0_release(int mem) {
}

void MPC_SOLVER_dynamics_0_incref(void) {
}

void MPC_SOLVER_dynamics_0_decref(void) {
}

casadi_int MPC_SOLVER_dynamics_0_n_in(void) { return 2;}

casadi_int MPC_SOLVER_dynamics_0_n_out(void) { return 2;}

casadi_real MPC_SOLVER_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* MPC_SOLVER_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* MPC_SOLVER_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int MPC_SOLVER_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* MPC_SOLVER_inequalities_0:(i0[7],i1[26])->(o0[6],o1[6x7,17nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][4] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][0] : 0;
  a3=(a2-a3);
  a4=(a1*a3);
  a5=sin(a0);
  a6=arg[0]? arg[0][4] : 0;
  a7=arg[1]? arg[1][1] : 0;
  a7=(a6-a7);
  a8=(a5*a7);
  a4=(a4+a8);
  a8=casadi_sq(a4);
  a9=arg[1]? arg[1][3] : 0;
  a10=5.;
  a11=(a9+a10);
  a11=casadi_sq(a11);
  a8=(a8*a11);
  a12=cos(a0);
  a7=(a12*a7);
  a0=sin(a0);
  a3=(a0*a3);
  a7=(a7-a3);
  a3=casadi_sq(a7);
  a13=arg[1]? arg[1][2] : 0;
  a14=(a13+a10);
  a14=casadi_sq(a14);
  a3=(a3*a14);
  a8=(a8+a3);
  a13=(a13+a10);
  a9=(a9+a10);
  a13=(a13*a9);
  a13=casadi_sq(a13);
  a8=(a8-a13);
  a13=arg[0]? arg[0][0] : 0;
  a8=(a8+a13);
  if (res[0]!=0) res[0][0]=a8;
  a8=arg[1]? arg[1][9] : 0;
  a9=cos(a8);
  a3=arg[1]? arg[1][5] : 0;
  a3=(a2-a3);
  a15=(a9*a3);
  a16=sin(a8);
  a17=arg[1]? arg[1][6] : 0;
  a17=(a6-a17);
  a18=(a16*a17);
  a15=(a15+a18);
  a18=casadi_sq(a15);
  a19=arg[1]? arg[1][8] : 0;
  a20=(a19+a10);
  a20=casadi_sq(a20);
  a18=(a18*a20);
  a21=cos(a8);
  a17=(a21*a17);
  a8=sin(a8);
  a3=(a8*a3);
  a17=(a17-a3);
  a3=casadi_sq(a17);
  a22=arg[1]? arg[1][7] : 0;
  a23=(a22+a10);
  a23=casadi_sq(a23);
  a3=(a3*a23);
  a18=(a18+a3);
  a22=(a22+a10);
  a19=(a19+a10);
  a22=(a22*a19);
  a22=casadi_sq(a22);
  a18=(a18-a22);
  a18=(a18+a13);
  if (res[0]!=0) res[0][1]=a18;
  a18=arg[1]? arg[1][14] : 0;
  a22=cos(a18);
  a19=arg[1]? arg[1][10] : 0;
  a19=(a2-a19);
  a3=(a22*a19);
  a24=sin(a18);
  a25=arg[1]? arg[1][11] : 0;
  a25=(a6-a25);
  a26=(a24*a25);
  a3=(a3+a26);
  a26=casadi_sq(a3);
  a27=arg[1]? arg[1][13] : 0;
  a28=(a27+a10);
  a28=casadi_sq(a28);
  a26=(a26*a28);
  a29=cos(a18);
  a25=(a29*a25);
  a18=sin(a18);
  a19=(a18*a19);
  a25=(a25-a19);
  a19=casadi_sq(a25);
  a30=arg[1]? arg[1][12] : 0;
  a31=(a30+a10);
  a31=casadi_sq(a31);
  a19=(a19*a31);
  a26=(a26+a19);
  a30=(a30+a10);
  a27=(a27+a10);
  a30=(a30*a27);
  a30=casadi_sq(a30);
  a26=(a26-a30);
  a26=(a26+a13);
  if (res[0]!=0) res[0][2]=a26;
  a26=arg[1]? arg[1][19] : 0;
  a30=cos(a26);
  a27=arg[1]? arg[1][15] : 0;
  a27=(a2-a27);
  a19=(a30*a27);
  a32=sin(a26);
  a33=arg[1]? arg[1][16] : 0;
  a33=(a6-a33);
  a34=(a32*a33);
  a19=(a19+a34);
  a34=casadi_sq(a19);
  a35=arg[1]? arg[1][18] : 0;
  a36=(a35+a10);
  a36=casadi_sq(a36);
  a34=(a34*a36);
  a37=cos(a26);
  a33=(a37*a33);
  a26=sin(a26);
  a27=(a26*a27);
  a33=(a33-a27);
  a27=casadi_sq(a33);
  a38=arg[1]? arg[1][17] : 0;
  a39=(a38+a10);
  a39=casadi_sq(a39);
  a27=(a27*a39);
  a34=(a34+a27);
  a38=(a38+a10);
  a35=(a35+a10);
  a38=(a38*a35);
  a38=casadi_sq(a38);
  a34=(a34-a38);
  a34=(a34+a13);
  if (res[0]!=0) res[0][3]=a34;
  a34=arg[1]? arg[1][24] : 0;
  a38=cos(a34);
  a35=arg[1]? arg[1][20] : 0;
  a2=(a2-a35);
  a35=(a38*a2);
  a27=sin(a34);
  a40=arg[1]? arg[1][21] : 0;
  a6=(a6-a40);
  a40=(a27*a6);
  a35=(a35+a40);
  a40=casadi_sq(a35);
  a41=arg[1]? arg[1][23] : 0;
  a42=(a41+a10);
  a42=casadi_sq(a42);
  a40=(a40*a42);
  a43=cos(a34);
  a6=(a43*a6);
  a34=sin(a34);
  a2=(a34*a2);
  a6=(a6-a2);
  a2=casadi_sq(a6);
  a44=arg[1]? arg[1][22] : 0;
  a45=(a44+a10);
  a45=casadi_sq(a45);
  a2=(a2*a45);
  a40=(a40+a2);
  a44=(a44+a10);
  a41=(a41+a10);
  a44=(a44*a41);
  a44=casadi_sq(a44);
  a40=(a40-a44);
  a40=(a40+a13);
  if (res[0]!=0) res[0][4]=a40;
  a40=arg[0]? arg[0][5] : 0;
  a13=casadi_sq(a40);
  a44=arg[0]? arg[0][6] : 0;
  a41=casadi_sq(a44);
  a13=(a13+a41);
  a41=arg[1]? arg[1][25] : 0;
  a41=casadi_sq(a41);
  a13=(a13-a41);
  if (res[0]!=0) res[0][5]=a13;
  a13=1.;
  if (res[1]!=0) res[1][0]=a13;
  if (res[1]!=0) res[1][1]=a13;
  if (res[1]!=0) res[1][2]=a13;
  if (res[1]!=0) res[1][3]=a13;
  if (res[1]!=0) res[1][4]=a13;
  a4=(a4+a4);
  a1=(a4*a1);
  a1=(a11*a1);
  a7=(a7+a7);
  a0=(a7*a0);
  a0=(a14*a0);
  a1=(a1-a0);
  if (res[1]!=0) res[1][5]=a1;
  a15=(a15+a15);
  a9=(a15*a9);
  a9=(a20*a9);
  a17=(a17+a17);
  a8=(a17*a8);
  a8=(a23*a8);
  a9=(a9-a8);
  if (res[1]!=0) res[1][6]=a9;
  a3=(a3+a3);
  a22=(a3*a22);
  a22=(a28*a22);
  a25=(a25+a25);
  a18=(a25*a18);
  a18=(a31*a18);
  a22=(a22-a18);
  if (res[1]!=0) res[1][7]=a22;
  a19=(a19+a19);
  a30=(a19*a30);
  a30=(a36*a30);
  a33=(a33+a33);
  a26=(a33*a26);
  a26=(a39*a26);
  a30=(a30-a26);
  if (res[1]!=0) res[1][8]=a30;
  a35=(a35+a35);
  a38=(a35*a38);
  a38=(a42*a38);
  a6=(a6+a6);
  a34=(a6*a34);
  a34=(a45*a34);
  a38=(a38-a34);
  if (res[1]!=0) res[1][9]=a38;
  a4=(a4*a5);
  a11=(a11*a4);
  a7=(a7*a12);
  a14=(a14*a7);
  a11=(a11+a14);
  if (res[1]!=0) res[1][10]=a11;
  a15=(a15*a16);
  a20=(a20*a15);
  a17=(a17*a21);
  a23=(a23*a17);
  a20=(a20+a23);
  if (res[1]!=0) res[1][11]=a20;
  a3=(a3*a24);
  a28=(a28*a3);
  a25=(a25*a29);
  a31=(a31*a25);
  a28=(a28+a31);
  if (res[1]!=0) res[1][12]=a28;
  a19=(a19*a32);
  a36=(a36*a19);
  a33=(a33*a37);
  a39=(a39*a33);
  a36=(a36+a39);
  if (res[1]!=0) res[1][13]=a36;
  a35=(a35*a27);
  a42=(a42*a35);
  a6=(a6*a43);
  a45=(a45*a6);
  a42=(a42+a45);
  if (res[1]!=0) res[1][14]=a42;
  a40=(a40+a40);
  if (res[1]!=0) res[1][15]=a40;
  a44=(a44+a44);
  if (res[1]!=0) res[1][16]=a44;
  return 0;
}

int MPC_SOLVER_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int MPC_SOLVER_inequalities_0_alloc_mem(void) {
  return 0;
}

int MPC_SOLVER_inequalities_0_init_mem(int mem) {
  return 0;
}

void MPC_SOLVER_inequalities_0_free_mem(int mem) {
}

int MPC_SOLVER_inequalities_0_checkout(void) {
  return 0;
}

void MPC_SOLVER_inequalities_0_release(int mem) {
}

void MPC_SOLVER_inequalities_0_incref(void) {
}

void MPC_SOLVER_inequalities_0_decref(void) {
}

casadi_int MPC_SOLVER_inequalities_0_n_in(void) { return 2;}

casadi_int MPC_SOLVER_inequalities_0_n_out(void) { return 2;}

casadi_real MPC_SOLVER_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* MPC_SOLVER_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* MPC_SOLVER_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    default: return 0;
  }
}

int MPC_SOLVER_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* MPC_SOLVER_objective_1:(i0[7],i1[26])->(o0,o1[1x7,5nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=1.0000000000000001e-01;
  a1=arg[0]? arg[0][3] : 0;
  a2=240.;
  a3=(a1-a2);
  a3=(a0*a3);
  a1=(a1-a2);
  a2=(a3*a1);
  a4=arg[0]? arg[0][4] : 0;
  a5=605.;
  a6=(a4-a5);
  a6=(a0*a6);
  a4=(a4-a5);
  a5=(a6*a4);
  a2=(a2+a5);
  a5=arg[0]? arg[0][5] : 0;
  a7=(a0*a5);
  a8=(a7*a5);
  a2=(a2+a8);
  a8=arg[0]? arg[0][6] : 0;
  a9=(a0*a8);
  a10=(a9*a8);
  a2=(a2+a10);
  a10=arg[0]? arg[0][0] : 0;
  a2=(a2+a10);
  if (res[0]!=0) res[0][0]=a2;
  a2=1.;
  if (res[1]!=0) res[1][0]=a2;
  a1=(a0*a1);
  a3=(a3+a1);
  if (res[1]!=0) res[1][1]=a3;
  a4=(a0*a4);
  a6=(a6+a4);
  if (res[1]!=0) res[1][2]=a6;
  a5=(a0*a5);
  a7=(a7+a5);
  if (res[1]!=0) res[1][3]=a7;
  a0=(a0*a8);
  a9=(a9+a0);
  if (res[1]!=0) res[1][4]=a9;
  return 0;
}

int MPC_SOLVER_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int MPC_SOLVER_objective_1_alloc_mem(void) {
  return 0;
}

int MPC_SOLVER_objective_1_init_mem(int mem) {
  return 0;
}

void MPC_SOLVER_objective_1_free_mem(int mem) {
}

int MPC_SOLVER_objective_1_checkout(void) {
  return 0;
}

void MPC_SOLVER_objective_1_release(int mem) {
}

void MPC_SOLVER_objective_1_incref(void) {
}

void MPC_SOLVER_objective_1_decref(void) {
}

casadi_int MPC_SOLVER_objective_1_n_in(void) { return 2;}

casadi_int MPC_SOLVER_objective_1_n_out(void) { return 2;}

casadi_real MPC_SOLVER_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* MPC_SOLVER_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* MPC_SOLVER_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int MPC_SOLVER_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* MPC_SOLVER_inequalities_1:(i0[7],i1[26])->(o0[6],o1[6x7,17nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][4] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][3] : 0;
  a3=arg[1]? arg[1][0] : 0;
  a3=(a2-a3);
  a4=(a1*a3);
  a5=sin(a0);
  a6=arg[0]? arg[0][4] : 0;
  a7=arg[1]? arg[1][1] : 0;
  a7=(a6-a7);
  a8=(a5*a7);
  a4=(a4+a8);
  a8=casadi_sq(a4);
  a9=arg[1]? arg[1][3] : 0;
  a10=5.;
  a11=(a9+a10);
  a11=casadi_sq(a11);
  a8=(a8*a11);
  a12=cos(a0);
  a7=(a12*a7);
  a0=sin(a0);
  a3=(a0*a3);
  a7=(a7-a3);
  a3=casadi_sq(a7);
  a13=arg[1]? arg[1][2] : 0;
  a14=(a13+a10);
  a14=casadi_sq(a14);
  a3=(a3*a14);
  a8=(a8+a3);
  a13=(a13+a10);
  a9=(a9+a10);
  a13=(a13*a9);
  a13=casadi_sq(a13);
  a8=(a8-a13);
  a13=arg[0]? arg[0][0] : 0;
  a8=(a8+a13);
  if (res[0]!=0) res[0][0]=a8;
  a8=arg[1]? arg[1][9] : 0;
  a9=cos(a8);
  a3=arg[1]? arg[1][5] : 0;
  a3=(a2-a3);
  a15=(a9*a3);
  a16=sin(a8);
  a17=arg[1]? arg[1][6] : 0;
  a17=(a6-a17);
  a18=(a16*a17);
  a15=(a15+a18);
  a18=casadi_sq(a15);
  a19=arg[1]? arg[1][8] : 0;
  a20=(a19+a10);
  a20=casadi_sq(a20);
  a18=(a18*a20);
  a21=cos(a8);
  a17=(a21*a17);
  a8=sin(a8);
  a3=(a8*a3);
  a17=(a17-a3);
  a3=casadi_sq(a17);
  a22=arg[1]? arg[1][7] : 0;
  a23=(a22+a10);
  a23=casadi_sq(a23);
  a3=(a3*a23);
  a18=(a18+a3);
  a22=(a22+a10);
  a19=(a19+a10);
  a22=(a22*a19);
  a22=casadi_sq(a22);
  a18=(a18-a22);
  a18=(a18+a13);
  if (res[0]!=0) res[0][1]=a18;
  a18=arg[1]? arg[1][14] : 0;
  a22=cos(a18);
  a19=arg[1]? arg[1][10] : 0;
  a19=(a2-a19);
  a3=(a22*a19);
  a24=sin(a18);
  a25=arg[1]? arg[1][11] : 0;
  a25=(a6-a25);
  a26=(a24*a25);
  a3=(a3+a26);
  a26=casadi_sq(a3);
  a27=arg[1]? arg[1][13] : 0;
  a28=(a27+a10);
  a28=casadi_sq(a28);
  a26=(a26*a28);
  a29=cos(a18);
  a25=(a29*a25);
  a18=sin(a18);
  a19=(a18*a19);
  a25=(a25-a19);
  a19=casadi_sq(a25);
  a30=arg[1]? arg[1][12] : 0;
  a31=(a30+a10);
  a31=casadi_sq(a31);
  a19=(a19*a31);
  a26=(a26+a19);
  a30=(a30+a10);
  a27=(a27+a10);
  a30=(a30*a27);
  a30=casadi_sq(a30);
  a26=(a26-a30);
  a26=(a26+a13);
  if (res[0]!=0) res[0][2]=a26;
  a26=arg[1]? arg[1][19] : 0;
  a30=cos(a26);
  a27=arg[1]? arg[1][15] : 0;
  a27=(a2-a27);
  a19=(a30*a27);
  a32=sin(a26);
  a33=arg[1]? arg[1][16] : 0;
  a33=(a6-a33);
  a34=(a32*a33);
  a19=(a19+a34);
  a34=casadi_sq(a19);
  a35=arg[1]? arg[1][18] : 0;
  a36=(a35+a10);
  a36=casadi_sq(a36);
  a34=(a34*a36);
  a37=cos(a26);
  a33=(a37*a33);
  a26=sin(a26);
  a27=(a26*a27);
  a33=(a33-a27);
  a27=casadi_sq(a33);
  a38=arg[1]? arg[1][17] : 0;
  a39=(a38+a10);
  a39=casadi_sq(a39);
  a27=(a27*a39);
  a34=(a34+a27);
  a38=(a38+a10);
  a35=(a35+a10);
  a38=(a38*a35);
  a38=casadi_sq(a38);
  a34=(a34-a38);
  a34=(a34+a13);
  if (res[0]!=0) res[0][3]=a34;
  a34=arg[1]? arg[1][24] : 0;
  a38=cos(a34);
  a35=arg[1]? arg[1][20] : 0;
  a2=(a2-a35);
  a35=(a38*a2);
  a27=sin(a34);
  a40=arg[1]? arg[1][21] : 0;
  a6=(a6-a40);
  a40=(a27*a6);
  a35=(a35+a40);
  a40=casadi_sq(a35);
  a41=arg[1]? arg[1][23] : 0;
  a42=(a41+a10);
  a42=casadi_sq(a42);
  a40=(a40*a42);
  a43=cos(a34);
  a6=(a43*a6);
  a34=sin(a34);
  a2=(a34*a2);
  a6=(a6-a2);
  a2=casadi_sq(a6);
  a44=arg[1]? arg[1][22] : 0;
  a45=(a44+a10);
  a45=casadi_sq(a45);
  a2=(a2*a45);
  a40=(a40+a2);
  a44=(a44+a10);
  a41=(a41+a10);
  a44=(a44*a41);
  a44=casadi_sq(a44);
  a40=(a40-a44);
  a40=(a40+a13);
  if (res[0]!=0) res[0][4]=a40;
  a40=arg[0]? arg[0][5] : 0;
  a13=casadi_sq(a40);
  a44=arg[0]? arg[0][6] : 0;
  a41=casadi_sq(a44);
  a13=(a13+a41);
  a41=arg[1]? arg[1][25] : 0;
  a41=casadi_sq(a41);
  a13=(a13-a41);
  if (res[0]!=0) res[0][5]=a13;
  a13=1.;
  if (res[1]!=0) res[1][0]=a13;
  if (res[1]!=0) res[1][1]=a13;
  if (res[1]!=0) res[1][2]=a13;
  if (res[1]!=0) res[1][3]=a13;
  if (res[1]!=0) res[1][4]=a13;
  a4=(a4+a4);
  a1=(a4*a1);
  a1=(a11*a1);
  a7=(a7+a7);
  a0=(a7*a0);
  a0=(a14*a0);
  a1=(a1-a0);
  if (res[1]!=0) res[1][5]=a1;
  a15=(a15+a15);
  a9=(a15*a9);
  a9=(a20*a9);
  a17=(a17+a17);
  a8=(a17*a8);
  a8=(a23*a8);
  a9=(a9-a8);
  if (res[1]!=0) res[1][6]=a9;
  a3=(a3+a3);
  a22=(a3*a22);
  a22=(a28*a22);
  a25=(a25+a25);
  a18=(a25*a18);
  a18=(a31*a18);
  a22=(a22-a18);
  if (res[1]!=0) res[1][7]=a22;
  a19=(a19+a19);
  a30=(a19*a30);
  a30=(a36*a30);
  a33=(a33+a33);
  a26=(a33*a26);
  a26=(a39*a26);
  a30=(a30-a26);
  if (res[1]!=0) res[1][8]=a30;
  a35=(a35+a35);
  a38=(a35*a38);
  a38=(a42*a38);
  a6=(a6+a6);
  a34=(a6*a34);
  a34=(a45*a34);
  a38=(a38-a34);
  if (res[1]!=0) res[1][9]=a38;
  a4=(a4*a5);
  a11=(a11*a4);
  a7=(a7*a12);
  a14=(a14*a7);
  a11=(a11+a14);
  if (res[1]!=0) res[1][10]=a11;
  a15=(a15*a16);
  a20=(a20*a15);
  a17=(a17*a21);
  a23=(a23*a17);
  a20=(a20+a23);
  if (res[1]!=0) res[1][11]=a20;
  a3=(a3*a24);
  a28=(a28*a3);
  a25=(a25*a29);
  a31=(a31*a25);
  a28=(a28+a31);
  if (res[1]!=0) res[1][12]=a28;
  a19=(a19*a32);
  a36=(a36*a19);
  a33=(a33*a37);
  a39=(a39*a33);
  a36=(a36+a39);
  if (res[1]!=0) res[1][13]=a36;
  a35=(a35*a27);
  a42=(a42*a35);
  a6=(a6*a43);
  a45=(a45*a6);
  a42=(a42+a45);
  if (res[1]!=0) res[1][14]=a42;
  a40=(a40+a40);
  if (res[1]!=0) res[1][15]=a40;
  a44=(a44+a44);
  if (res[1]!=0) res[1][16]=a44;
  return 0;
}

int MPC_SOLVER_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int MPC_SOLVER_inequalities_1_alloc_mem(void) {
  return 0;
}

int MPC_SOLVER_inequalities_1_init_mem(int mem) {
  return 0;
}

void MPC_SOLVER_inequalities_1_free_mem(int mem) {
}

int MPC_SOLVER_inequalities_1_checkout(void) {
  return 0;
}

void MPC_SOLVER_inequalities_1_release(int mem) {
}

void MPC_SOLVER_inequalities_1_incref(void) {
}

void MPC_SOLVER_inequalities_1_decref(void) {
}

casadi_int MPC_SOLVER_inequalities_1_n_in(void) { return 2;}

casadi_int MPC_SOLVER_inequalities_1_n_out(void) { return 2;}

casadi_real MPC_SOLVER_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* MPC_SOLVER_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* MPC_SOLVER_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* MPC_SOLVER_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    default: return 0;
  }
}

int MPC_SOLVER_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
